// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamWebAPI.Data;

#nullable disable

namespace TeamWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423014532_SeedDataAndAnnotations")]
    partial class SeedDataAndAnnotations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamWebAPI.Models.BreakfastFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalorieCount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreparationTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BreakfastFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalorieCount = 320,
                            Category = "Toast",
                            IsHealthy = true,
                            Name = "Avocado Toast",
                            PreparationTime = "10 minutes"
                        },
                        new
                        {
                            Id = 2,
                            CalorieCount = 520,
                            Category = "Pastry",
                            IsHealthy = false,
                            Name = "Pancakes",
                            PreparationTime = "20 minutes"
                        },
                        new
                        {
                            Id = 3,
                            CalorieCount = 280,
                            Category = "Yogurt",
                            IsHealthy = true,
                            Name = "Greek Yogurt with Granola",
                            PreparationTime = "2 minutes"
                        },
                        new
                        {
                            Id = 4,
                            CalorieCount = 450,
                            Category = "Eggs",
                            IsHealthy = false,
                            Name = "Bacon and Eggs",
                            PreparationTime = "15 minutes"
                        },
                        new
                        {
                            Id = 5,
                            CalorieCount = 210,
                            Category = "Cereal",
                            IsHealthy = true,
                            Name = "Oatmeal with Berries",
                            PreparationTime = "5 minutes"
                        },
                        new
                        {
                            Id = 6,
                            CalorieCount = 580,
                            Category = "Wrap",
                            IsHealthy = false,
                            Name = "Breakfast Burrito",
                            PreparationTime = "15 minutes"
                        });
                });

            modelBuilder.Entity("TeamWebAPI.Models.FavoriteMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteMovies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            Rating = 9.0,
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Rating = 8.5999999999999996,
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 4,
                            Director = "Bong Joon-ho",
                            Genre = "Thriller",
                            Rating = 8.5,
                            ReleaseYear = 2019,
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 5,
                            Director = "The Wachowskis",
                            Genre = "Sci-Fi",
                            Rating = 8.6999999999999993,
                            ReleaseYear = 1999,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 6,
                            Director = "Hayao Miyazaki",
                            Genre = "Animation",
                            Rating = 8.5999999999999996,
                            ReleaseYear = 2001,
                            Title = "Spirited Away"
                        });
                });

            modelBuilder.Entity("TeamWebAPI.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsActive")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Creative",
                            Description = "Capturing moments with a DSLR camera",
                            Name = "Photography",
                            SkillLevel = "Intermediate",
                            YearsActive = 4
                        },
                        new
                        {
                            Id = 2,
                            Category = "Outdoor",
                            Description = "Indoor and outdoor bouldering and sport climbing",
                            Name = "Rock Climbing",
                            SkillLevel = "Beginner",
                            YearsActive = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Indoor",
                            Description = "Competitive chess player, online and in-person",
                            Name = "Chess",
                            SkillLevel = "Advanced",
                            YearsActive = 10
                        },
                        new
                        {
                            Id = 4,
                            Category = "Creative",
                            Description = "Acrylic and watercolor painting on canvas",
                            Name = "Painting",
                            SkillLevel = "Intermediate",
                            YearsActive = 6
                        },
                        new
                        {
                            Id = 5,
                            Category = "Outdoor",
                            Description = "Weekend trail hiking in national parks",
                            Name = "Hiking",
                            SkillLevel = "Intermediate",
                            YearsActive = 3
                        },
                        new
                        {
                            Id = 6,
                            Category = "Indoor",
                            Description = "PC and console gaming, mostly RPGs and strategy",
                            Name = "Gaming",
                            SkillLevel = "Advanced",
                            YearsActive = 8
                        });
                });

            modelBuilder.Entity("TeamWebAPI.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2002, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Computer Science",
                            Email = "alex.johnson@school.edu",
                            FullName = "Alex Johnson",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2003, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Engineering",
                            Email = "maria.garcia@school.edu",
                            FullName = "Maria Garcia",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(2001, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            Email = "james.lee@school.edu",
                            FullName = "James Lee",
                            YearInProgram = "Senior"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(2004, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Computer Science",
                            Email = "priya.patel@school.edu",
                            FullName = "Priya Patel",
                            YearInProgram = "Freshman"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(2002, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Cybersecurity",
                            Email = "tyler.brooks@school.edu",
                            FullName = "Tyler Brooks",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 6,
                            Birthdate = new DateTime(2003, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Data Science",
                            Email = "samantha.wu@school.edu",
                            FullName = "Samantha Wu",
                            YearInProgram = "Sophomore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
