// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamWebAPI.Data;

#nullable disable

namespace TeamWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamWebAPI.Models.BreakfastFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PreparationTimeMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BreakfastFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 250,
                            Cuisine = "American",
                            IsHealthy = true,
                            Name = "Avocado Toast",
                            PreparationTimeMinutes = 10
                        },
                        new
                        {
                            Id = 2,
                            Calories = 450,
                            Cuisine = "American",
                            IsHealthy = false,
                            Name = "Pancakes",
                            PreparationTimeMinutes = 20
                        },
                        new
                        {
                            Id = 3,
                            Calories = 320,
                            Cuisine = "European",
                            IsHealthy = true,
                            Name = "Overnight Oats",
                            PreparationTimeMinutes = 5
                        },
                        new
                        {
                            Id = 4,
                            Calories = 550,
                            Cuisine = "Mexican",
                            IsHealthy = false,
                            Name = "Breakfast Burrito",
                            PreparationTimeMinutes = 15
                        },
                        new
                        {
                            Id = 5,
                            Calories = 380,
                            Cuisine = "Brazilian",
                            IsHealthy = true,
                            Name = "Acai Bowl",
                            PreparationTimeMinutes = 8
                        });
                });

            modelBuilder.Entity("TeamWebAPI.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsOutdoor")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Outdoor",
                            Description = "Trekking through natural trails",
                            DifficultyLevel = "Medium",
                            IsOutdoor = true,
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Creative",
                            Description = "Creating art with various paint media",
                            DifficultyLevel = "Easy",
                            IsOutdoor = false,
                            Name = "Painting"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Sports",
                            Description = "Scaling natural and artificial rock faces",
                            DifficultyLevel = "Hard",
                            IsOutdoor = true,
                            Name = "Rock Climbing"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Indoor",
                            Description = "Exploring books across all genres",
                            DifficultyLevel = "Easy",
                            IsOutdoor = false,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Creative",
                            Description = "Capturing moments through a lens",
                            DifficultyLevel = "Medium",
                            IsOutdoor = false,
                            Name = "Photography"
                        });
                });

            modelBuilder.Entity("TeamWebAPI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            Rating = 9.0,
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Rating = 8.5999999999999996,
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 4,
                            Director = "Bong Joon-ho",
                            Genre = "Thriller",
                            Rating = 8.5,
                            ReleaseYear = 2019,
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 5,
                            Director = "Frank Darabont",
                            Genre = "Drama",
                            Rating = 9.3000000000000007,
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption"
                        });
                });

            modelBuilder.Entity("TeamWebAPI.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2002, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Computer Science",
                            Email = "alice@example.com",
                            FullName = "Alice Johnson",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2001, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Engineering",
                            Email = "bob@example.com",
                            FullName = "Bob Smith",
                            YearInProgram = "Senior"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(2003, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            Email = "carol@example.com",
                            FullName = "Carol Davis",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(2004, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Cybersecurity",
                            Email = "david@example.com",
                            FullName = "David Lee",
                            YearInProgram = "Freshman"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(2000, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Data Science",
                            Email = "emma@example.com",
                            FullName = "Emma Wilson",
                            YearInProgram = "Senior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
