// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentWebAPI.Data;

#nullable disable

namespace StudentWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("StudentWebAPI.Models.BreakfastFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaloriesPerServing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSweet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparationTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BreakfastFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPerServing = 350,
                            Cuisine = "American",
                            IsSweet = true,
                            Name = "Pancakes",
                            PreparationTime = "20 minutes"
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPerServing = 250,
                            Cuisine = "Modern",
                            IsSweet = false,
                            Name = "Avocado Toast",
                            PreparationTime = "10 minutes"
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPerServing = 450,
                            Cuisine = "American",
                            IsSweet = false,
                            Name = "Eggs Benedict",
                            PreparationTime = "25 minutes"
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPerServing = 300,
                            Cuisine = "Brazilian",
                            IsSweet = true,
                            Name = "Acai Bowl",
                            PreparationTime = "5 minutes"
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPerServing = 270,
                            Cuisine = "French",
                            IsSweet = false,
                            Name = "Croissant",
                            PreparationTime = "2 minutes"
                        });
                });

            modelBuilder.Entity("StudentWebAPI.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageHoursPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresEquipment")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageHoursPerWeek = 5,
                            Category = "Outdoor",
                            Description = "Scaling natural or artificial rock walls.",
                            Name = "Rock Climbing",
                            RequiresEquipment = true
                        },
                        new
                        {
                            Id = 2,
                            AverageHoursPerWeek = 4,
                            Category = "Creative",
                            Description = "Expressing art using paint and canvas.",
                            Name = "Painting",
                            RequiresEquipment = true
                        },
                        new
                        {
                            Id = 3,
                            AverageHoursPerWeek = 7,
                            Category = "Indoor",
                            Description = "Enjoying books of various genres.",
                            Name = "Reading",
                            RequiresEquipment = false
                        },
                        new
                        {
                            Id = 4,
                            AverageHoursPerWeek = 6,
                            Category = "Outdoor",
                            Description = "Riding bicycles for fitness or leisure.",
                            Name = "Cycling",
                            RequiresEquipment = true
                        },
                        new
                        {
                            Id = 5,
                            AverageHoursPerWeek = 3,
                            Category = "Indoor",
                            Description = "Strategic board game for two players.",
                            Name = "Chess",
                            RequiresEquipment = true
                        });
                });

            modelBuilder.Entity("StudentWebAPI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            Rating = 9.0,
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Rating = 8.5999999999999996,
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 4,
                            Director = "Bong Joon-ho",
                            Genre = "Thriller",
                            Rating = 8.5,
                            ReleaseYear = 2019,
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 5,
                            Director = "Frank Darabont",
                            Genre = "Drama",
                            Rating = 9.3000000000000007,
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption"
                        });
                });

            modelBuilder.Entity("StudentWebAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2002, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Computer Science",
                            Email = "rohit.vijay@college.edu",
                            FullName = "Rohit Vijay",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2001, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Engineering",
                            Email = "alex.johnson@college.edu",
                            FullName = "Alex Johnson",
                            YearInProgram = "Senior"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(2003, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Data Science",
                            Email = "maria.garcia@college.edu",
                            FullName = "Maria Garcia",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(2004, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Cybersecurity",
                            Email = "liam.patel@college.edu",
                            FullName = "Liam Patel",
                            YearInProgram = "Freshman"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(2000, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Computer Science",
                            Email = "sara.kim@college.edu",
                            FullName = "Sara Kim",
                            YearInProgram = "Senior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
